"""Convert PCG source HTML files to Markdown.

Uses the html-to-markdown library (Rust-powered, CommonMark compliant)
to convert the positioned-layout HTML files generated by pdf2html.py
into clean Markdown.

Usage:
    uv run html2md.py [--year YEAR] [--all] [--output-dir DIR]

Examples:
    uv run html2md.py --year 2026          # Convert HTMLs for a specific year
    uv run html2md.py --all                # Convert all HTMLs across all years
    uv run html2md.py --all --output-dir out  # Specify a custom output directory
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from html_to_markdown import ConversionOptions, convert

SOURCES_DIR = Path(__file__).resolve().parent.parent / "sources"

# Options tuned for our positioned-layout HTML sources.
_OPTIONS = ConversionOptions(
    heading_style="atx",
    strip_tags=["img"],
)


def convert_html_to_md(html_path: Path, md_path: Path) -> None:
    """Convert a single HTML file to Markdown."""
    html = html_path.read_text(encoding="utf-8")
    markdown = convert(html, options=_OPTIONS)
    md_path.write_text(markdown, encoding="utf-8")


def discover_htmls(year: str | None) -> list[Path]:
    """Find HTML files in the sources directory, optionally filtered by year."""
    if year:
        year_dir = SOURCES_DIR / year
        if not year_dir.is_dir():
            print(
                f"Error: no source directory found for year {year} at {year_dir}",
                file=sys.stderr,
            )
            sys.exit(1)
        return sorted(year_dir.glob("*.html"))

    # All years
    return sorted(SOURCES_DIR.rglob("*.html"))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert PCG source HTML files to Markdown.",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--year", help="Year to process (e.g. 2026)")
    group.add_argument("--all", action="store_true", help="Process all years")
    parser.add_argument(
        "--output-dir",
        default=None,
        help=(
            "Output directory for Markdown files "
            "(default: same directory as source HTML)"
        ),
    )

    args = parser.parse_args()

    htmls = discover_htmls(args.year if not args.all else None)

    if not htmls:
        print("No HTML files found.", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(htmls)} HTML(s) to convert.\n")

    for html_path in htmls:
        if args.output_dir:
            out_dir = Path(args.output_dir)
            relative = html_path.relative_to(SOURCES_DIR)
            md_path = out_dir / relative.with_suffix(".md")
        else:
            md_path = html_path.with_suffix(".md")

        md_path.parent.mkdir(parents=True, exist_ok=True)

        print(f"  {html_path.relative_to(SOURCES_DIR)} -> {md_path}")
        try:
            convert_html_to_md(html_path, md_path)
        except Exception as exc:
            print(f"    ERROR: {exc}", file=sys.stderr)
            continue

    print("\nDone.")


if __name__ == "__main__":
    main()
